version: '3.7'
services:
  expense-tracker:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://expense_user:password@db/expense_tracker
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expense_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  postgres_exporter:
      image: prometheuscommunity/postgres-exporter
      container_name: postgres_exporter
      environment:
        DATA_SOURCE_NAME: "postgresql://expense_user:password@db:5432/expense_tracker?sslmode=disable"
      depends_on:
        - db
        - prometheus
      ports:
        - "9187:9187"

volumes:
  postgres_data:
  grafana_data:

