name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start SSH agent and add private key
      run: |
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        # Debugging: List the added SSH keys
        ssh-add -l
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH Connection
      run: |
        # Debugging: Test the SSH connection with verbose output
        ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'echo "SSH connection successful!"'
        
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest
        cd /home/ubuntu/expense-tracker
        docker-compose down
        docker-compose up -d
        EOF

    env:
      SSH_USER: ubuntu  # Replace with your SSH user
      SSH_HOST: 3.10.175.69  # Replace with your EC2 instance's public IP
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

